CREATE TABLE User_Accounts(
First_Name VARCHAR(30) NOT NULL,
Last_Name VARCHAR(30) NOT NULL,
Login VARCHAR(255),
Password VARCHAR(255),
Email VARCHAR(60) NOT NULL PRIMARY KEY,
City VARCHAR(40) NOT NULL,
State CHAR(40) NOT NULL,
User_ID INT UNSIGNED,
Games_Won INT(11) NOT NULL,
Games_Lost INT(11) NOT NULL,
Experience INT(11) NOT NULL,
Reliability INT(11) NOT NULL);


